#Properties saved on 2026-04-08T20:09:16.135039286Z
#Wed Apr 08 20:09:16 UTC 2026
hoodie.compaction.payload.class=org.apache.hudi.metadata.HoodieMetadataPayload
hoodie.table.initial.version=9
hoodie.table.keygenerator.type=HOODIE_TABLE_METADATA
hoodie.table.type=MERGE_ON_READ
hoodie.archivelog.folder=history
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=2467640086
hoodie.datasource.write.drop.partition.columns=false
hoodie.record.merge.strategy.id=00000000-0000-0000-0000-000000000000
hoodie.table.recordkey.fields=key
hoodie.table.name=htestmergemodecommittimeordering_6_metadata
hoodie.timeline.path=timeline
hoodie.populate.meta.fields=false
hoodie.table.base.file.format=HFILE
hoodie.record.merge.mode=CUSTOM
hoodie.table.version=9
