#Properties saved on 2026-04-09T19:02:18.763753697Z
#Thu Apr 09 19:02:18 UTC 2026
hoodie.compaction.payload.class=org.apache.hudi.metadata.HoodieMetadataPayload
hoodie.table.initial.version=9
hoodie.table.keygenerator.type=HOODIE_TABLE_METADATA
hoodie.table.type=MERGE_ON_READ
hoodie.archivelog.folder=history
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=3213468893
hoodie.datasource.write.drop.partition.columns=false
hoodie.record.merge.strategy.id=00000000-0000-0000-0000-000000000000
hoodie.table.recordkey.fields=key
hoodie.table.name=hoodie_test_metadata
hoodie.timeline.path=timeline
hoodie.populate.meta.fields=false
hoodie.table.base.file.format=HFILE
hoodie.record.merge.mode=CUSTOM
hoodie.table.version=9
