#Updated at 2026-04-09T17:45:39.464457738Z
#Thu Apr 09 17:45:39 UTC 2026
hoodie.table.initial.version=9
hoodie.table.keygenerator.type=NON_PARTITION
hoodie.table.type=MERGE_ON_READ
hoodie.table.metadata.partitions=column_stats,files
hoodie.archivelog.folder=archived
hoodie.table.create.schema={"type"\:"record","name"\:"htestmorfileslicelayouts_5_record","namespace"\:"hoodie.htestmorfileslicelayouts_5","fields"\:[{"name"\:"key","type"\:["null","string"],"default"\:null},{"name"\:"ts","type"\:["null","long"],"default"\:null},{"name"\:"map_int","type"\:["null",{"type"\:"map","values"\:["null","int"]}],"default"\:null},{"name"\:"arr_bool","type"\:["null",{"type"\:"array","items"\:["null","boolean"]}],"default"\:null},{"name"\:"arr_tinyint","type"\:["null",{"type"\:"array","items"\:["null","int"]}],"default"\:null},{"name"\:"arr_small","type"\:["null",{"type"\:"array","items"\:["null","int"]}],"default"\:null},{"name"\:"arr_int","type"\:["null",{"type"\:"array","items"\:["null","int"]}],"default"\:null},{"name"\:"arr_float","type"\:["null",{"type"\:"array","items"\:["null","float"]}],"default"\:null},{"name"\:"arr_bigint","type"\:["null",{"type"\:"array","items"\:["null","long"]}],"default"\:null},{"name"\:"arr_double","type"\:["null",{"type"\:"array","items"\:["null","double"]}],"default"\:null},{"name"\:"partition","type"\:["null","string"],"default"\:null}]}
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=2236581349
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.recordkey.fields=key
hoodie.table.name=htestmorfileslicelayouts_5
hoodie.table.format=native
hoodie.timeline.path=timeline
hoodie.datasource.write.hive_style_partitioning=true
hoodie.table.metadata.partitions.inflight=
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
hoodie.database.name=default
hoodie.record.merge.mode=COMMIT_TIME_ORDERING
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.table.version=9
