#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Member names are mirrored from the Rust enums; the actual key strings
# live solely in `crates/core/src/config/{table,read}.rs` and are bound
# at import time by `python/hudi/_config.py`. Keep names in sync when a
# Rust variant is added.

from enum import Enum

class HudiTableConfig(str, Enum):
    """Configurations for Hudi tables, most of them are persisted in `hoodie.properties`."""

    BASE_FILE_FORMAT = ...
    BASE_PATH = ...
    CHECKSUM = ...
    CREATE_SCHEMA = ...
    DATABASE_NAME = ...
    DROPS_PARTITION_FIELDS = ...
    IS_HIVE_STYLE_PARTITIONING = ...
    IS_PARTITION_PATH_URLENCODED = ...
    KEY_GENERATOR_CLASS = ...
    KEY_GENERATOR_TYPE = ...
    PARTITION_FIELDS = ...
    PRECOMBINE_FIELD = ...
    POPULATES_META_FIELDS = ...
    RECORD_KEY_FIELDS = ...
    RECORD_MERGE_STRATEGY = ...
    TABLE_NAME = ...
    TABLE_TYPE = ...
    TABLE_VERSION = ...
    TIMELINE_LAYOUT_VERSION = ...
    TIMELINE_TIMEZONE = ...
    ARCHIVE_LOG_FOLDER = ...
    TIMELINE_PATH = ...
    TIMELINE_HISTORY_PATH = ...
    METADATA_TABLE_ENABLED = ...
    METADATA_TABLE_PARTITIONS = ...

class HudiReadConfig(str, Enum):
    """Configurations for reading Hudi tables."""

    FILE_GROUP_START_TIMESTAMP = ...
    FILE_GROUP_END_TIMESTAMP = ...
    INPUT_PARTITIONS = ...
    LISTING_PARALLELISM = ...
    USE_READ_OPTIMIZED_MODE = ...
    STREAM_BATCH_SIZE = ...
