#Properties saved on 2026-04-09T02:29:32.427676069Z
#Thu Apr 09 02:29:32 UTC 2026
hoodie.compaction.payload.class=org.apache.hudi.common.model.OverwriteWithLatestAvroPayload
hoodie.table.keygenerator.type=NON_PARTITION
hoodie.table.type=MERGE_ON_READ
hoodie.archivelog.folder=archived
hoodie.table.create.schema={"type"\:"record","name"\:"htestmorfileslicelayouts_1_record","namespace"\:"hoodie.htestmorfileslicelayouts_1","fields"\:[{"name"\:"key","type"\:["null","string"],"default"\:null},{"name"\:"ts","type"\:["null","long"],"default"\:null},{"name"\:"level","type"\:["null","string"],"default"\:null},{"name"\:"severity","type"\:["null","int"],"default"\:null},{"name"\:"partition","type"\:["null","string"],"default"\:null},{"name"\:"round","type"\:["null","int"],"default"\:null}]}
hoodie.timeline.layout.version=1
hoodie.timeline.history.path=history
hoodie.table.checksum=2183283196
hoodie.datasource.write.drop.partition.columns=false
hoodie.record.merge.strategy.id=ce9acb64-bde0-424c-9b91-f6ebba25356d
hoodie.table.format=native
hoodie.table.name=htestmorfileslicelayouts_1
hoodie.table.recordkey.fields=key
hoodie.timeline.path=timeline
hoodie.datasource.write.hive_style_partitioning=true
hoodie.database.name=default
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.table.version=6
