#Updated at 2026-04-09T02:43:44.290489903Z
#Thu Apr 09 02:43:44 UTC 2026
hoodie.table.initial.version=9
hoodie.table.keygenerator.type=NON_PARTITION
hoodie.table.type=MERGE_ON_READ
hoodie.table.metadata.partitions=column_stats,files
hoodie.archivelog.folder=archived
hoodie.table.create.schema={"type"\:"record","name"\:"htestmergemodecommittimeordering_6_record","namespace"\:"hoodie.htestmergemodecommittimeordering_6","fields"\:[{"name"\:"id","type"\:["null","int"],"default"\:null},{"name"\:"name","type"\:["null","string"],"default"\:null},{"name"\:"price","type"\:["null","double"],"default"\:null},{"name"\:"ts","type"\:["null","long"],"default"\:null}]}
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=1186674926
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.recordkey.fields=id
hoodie.table.name=htestmergemodecommittimeordering_6
hoodie.table.format=native
hoodie.timeline.path=timeline
hoodie.datasource.write.hive_style_partitioning=true
hoodie.table.metadata.partitions.inflight=
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
hoodie.database.name=default
hoodie.record.merge.mode=COMMIT_TIME_ORDERING
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.table.version=9
