{"namespace": "org.apache.hudi.avro.model",
 "type": "record",
 "name": "HoodieRollbackMetadata",
 "fields": [
     {"name": "startRollbackTime", "type": "string"},
     {"name": "timeTakenInMillis", "type": "long"},
     {"name": "totalFilesDeleted", "type": "int"},
     {"name": "commitsRollback", "type": {"type": "array", "items": "string"}},
     {"name": "partitionMetadata", "type": {
     "type" : "map", "values" : {
        "type": "record",
        "name": "HoodieRollbackPartitionMetadata",
        "fields": [
            {"name": "partitionPath", "type": "string"},
            {"name": "successDeleteFiles", "type": {"type": "array", "items": "string"}},
            {"name": "failedDeleteFiles", "type": {"type": "array", "items": "string"}},
            {"name": "rollbackLogFiles", "type": ["null", {
                "type": "map",
                "doc": "Files to which append blocks were written to capture rollback commit",
                "values": {
                    "type": "long",
                    "doc": "Size of this file in bytes"
                }
            }], "default":null },
            {"name": "logFilesFromFailedCommit",
             "type": ["null", {
               "type": "map",
               "doc": "Log files from the failed commit(commit to be rolled back)",
               "values": {
                   "type": "long",
                   "doc": "Size of this file in bytes"
               }
             }],
             "default":null
            }
        ]
     }}},
     {
        "name":"version",
        "type":["int", "null"],
        "default": 1
     },
     
     {
       "name": "instantsRollback",
       "default": [],
       "type": {
          "type": "array",
          "default": [],
          "items": "HoodieInstantInfo"
       }
     }
 ]
}
