#Updated at 2026-04-09T19:02:21.652896101Z
#Thu Apr 09 19:02:21 UTC 2026
hoodie.table.keygenerator.type=SIMPLE
hoodie.table.type=MERGE_ON_READ
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=2453301480
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.format=native
hoodie.table.legacy.payload.class=org.apache.hudi.common.model.DefaultHoodieRecordPayload
hoodie.table.partition_extractor_class=org.apache.hudi.hive.SinglePartPartitionValueExtractor
hoodie.datasource.write.hive_style_partitioning=false
hoodie.table.metadata.partitions.inflight=
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.record.merge.mode=EVENT_TIME_ORDERING
hoodie.table.version=9
hoodie.table.initial.version=9
hoodie.table.metadata.partitions=column_stats,files,partition_stats
hoodie.table.partition.fields=partition_path
hoodie.archivelog.folder=history
hoodie.table.cdc.enabled=false
hoodie.table.multiple.base.file.formats.enable=false
hoodie.table.timeline.timezone=LOCAL
hoodie.table.name=hoodie_test
hoodie.table.recordkey.fields=_row_key
hoodie.timeline.path=timeline
hoodie.table.ordering.fields=timestamp
hoodie.partition.metafile.use.base.format=false
hoodie.populate.meta.fields=true
hoodie.table.base.file.format=PARQUET
