/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//! Metadata table bootstrap and files / record_index partition updates.

use std::collections::{BTreeMap, HashMap};

use crate::Result;
use crate::file_group::log_file::writer::LogFileWriter;
use crate::file_group::log_file::{BlockMetadataKey, BlockType};
use crate::hfile::HFileWriter;
use crate::metadata::table::encode::{
    FilesMetadataEntry, RecordIndexEntry, encode_all_partitions, encode_files_record,
    encode_record_index_entry, files_metadata_avro_schema_json,
    record_index_metadata_avro_schema_json,
};
use crate::metadata::table::records::{FilesPartitionRecord, MetadataRecordType};
use crate::storage::Storage;
use crate::timeline::instant::Instant;

const METADATA_BASE: &str = ".hoodie/metadata";
const FILES_FILE_ID: &str = "files-0000-0";
const RECORD_INDEX_FILE_ID: &str = "record-index-0000-0";

/// Create the metadata table properties and its initial partitions.
pub async fn bootstrap_metadata_table(
    data_table_storage: &Storage,
    table_name: &str,
    instant: &str,
    record_index_enabled: bool,
) -> Result<()> {
    let mdt_name = format!("{table_name}_metadata");
    let checksum = crc32(format!(".{mdt_name}").as_bytes());
    let properties = format!(
        "# Generated by hudi-rs\n\
         hoodie.table.name={mdt_name}\n\
         hoodie.table.type=MERGE_ON_READ\n\
         hoodie.table.base.file.format=HFILE\n\
         hoodie.table.recordkey.fields=key\n\
         hoodie.populate.meta.fields=false\n\
         hoodie.table.version=8\n\
         hoodie.table.initial.version=8\n\
         hoodie.timeline.layout.version=2\n\
         hoodie.timeline.path=timeline\n\
         hoodie.timeline.history.path=history\n\
         hoodie.archivelog.folder=history\n\
         hoodie.table.keygenerator.type=HOODIE_TABLE_METADATA\n\
         hoodie.compaction.payload.class=org.apache.hudi.metadata.HoodieMetadataPayload\n\
         hoodie.record.merge.mode=CUSTOM\n\
         hoodie.record.merge.strategy.id=00000000-0000-0000-0000-000000000000\n\
         hoodie.datasource.write.drop.partition.columns=false\n\
         hoodie.table.checksum={checksum}\n"
    );
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/.hoodie/hoodie.properties"),
            properties.into_bytes(),
        )
        .await?;
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/.hoodie/timeline/.keep"),
            b"".as_slice(),
        )
        .await?;

    let empty_files = encode_files_record(
        FilesPartitionRecord::NON_PARTITIONED_NAME,
        MetadataRecordType::Files,
        Vec::<FilesMetadataEntry>::new(),
    )?;
    let all_partitions =
        encode_all_partitions(vec![FilesPartitionRecord::NON_PARTITIONED_NAME.to_string()])?;
    let hfile = HFileWriter::write(
        &[
            (
                FilesPartitionRecord::ALL_PARTITIONS_KEY.to_string(),
                all_partitions,
            ),
            (
                FilesPartitionRecord::NON_PARTITIONED_NAME.to_string(),
                empty_files,
            ),
        ],
        BTreeMap::from([(
            "schema".to_string(),
            files_metadata_avro_schema_json().as_bytes().to_vec(),
        )]),
    )
    .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/files/{FILES_FILE_ID}_0-0-0_{instant}.hfile"),
            hfile,
        )
        .await?;

    if record_index_enabled {
        let empty_rli = HFileWriter::write(
            &[],
            BTreeMap::from([(
                "schema".to_string(),
                record_index_metadata_avro_schema_json().as_bytes().to_vec(),
            )]),
        )
        .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
        data_table_storage
            .put_file(
                &format!(
                    "{METADATA_BASE}/record_index/{RECORD_INDEX_FILE_ID}_0-0-0_{instant}.hfile"
                ),
                empty_rli,
            )
            .await?;
    }

    write_metadata_commit(data_table_storage, instant).await
}

/// Append a files-partition HFile data block to the metadata table log file.
pub async fn update_files_partition(
    data_storage: &Storage,
    instant: &str,
    files: &[(String, String, i64)],
) -> Result<()> {
    let entries = files
        .iter()
        .map(|(partition, file_name, size)| (partition.clone(), file_name.clone(), *size, false))
        .collect::<Vec<_>>();
    update_files_partition_entries(data_storage, instant, &entries).await
}

/// Apply file additions and deletions to the metadata table files partition.
pub async fn update_files_partition_entries(
    data_storage: &Storage,
    instant: &str,
    files: &[(String, String, i64, bool)],
) -> Result<()> {
    let mut by_partition: BTreeMap<String, Vec<FilesMetadataEntry>> = BTreeMap::new();
    for (partition, file_name, size, is_deleted) in files {
        let partition = if partition.is_empty() {
            FilesPartitionRecord::NON_PARTITIONED_NAME.to_string()
        } else {
            partition.clone()
        };
        by_partition
            .entry(partition)
            .or_default()
            .push(FilesMetadataEntry {
                name: file_name.clone(),
                size: *size,
                is_deleted: *is_deleted,
            });
    }
    let partitions = by_partition.keys().cloned().collect::<Vec<_>>();
    let mut entries = vec![(
        FilesPartitionRecord::ALL_PARTITIONS_KEY.to_string(),
        encode_all_partitions(partitions)?,
    )];
    for (partition, files) in by_partition {
        entries.push((
            partition.clone(),
            encode_files_record(&partition, MetadataRecordType::Files, files)?,
        ));
    }
    let hfile = HFileWriter::write(
        &entries,
        BTreeMap::from([(
            "schema".to_string(),
            files_metadata_avro_schema_json().as_bytes().to_vec(),
        )]),
    )
    .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
    let block = LogFileWriter::write_log_block(
        BlockType::HfileData,
        HashMap::from([(BlockMetadataKey::InstantTime, instant.to_string())]),
        &hfile,
    );
    data_storage
        .put_file(
            &format!("{METADATA_BASE}/files/.{FILES_FILE_ID}_{instant}.log.1_0-0-0"),
            block,
        )
        .await?;
    write_metadata_commit(data_storage, instant).await
}

/// Append record-index put/delete entries as an HFile data log block.
pub async fn update_record_index(
    data_storage: &Storage,
    instant: &str,
    entries: &[RecordIndexEntry],
) -> Result<()> {
    if entries.is_empty() {
        return Ok(());
    }
    let mut pairs = Vec::with_capacity(entries.len());
    for entry in entries {
        let bytes = encode_record_index_entry(entry)?;
        pairs.push((entry.record_key.clone(), bytes));
    }
    let hfile = HFileWriter::write(
        &pairs,
        BTreeMap::from([(
            "schema".to_string(),
            record_index_metadata_avro_schema_json().as_bytes().to_vec(),
        )]),
    )
    .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
    let block = LogFileWriter::write_log_block(
        BlockType::HfileData,
        HashMap::from([(BlockMetadataKey::InstantTime, instant.to_string())]),
        &hfile,
    );
    data_storage
        .put_file(
            &format!(
                "{METADATA_BASE}/record_index/.{RECORD_INDEX_FILE_ID}_{instant}.log.1_0-0-0"
            ),
            block,
        )
        .await?;
    write_metadata_commit(data_storage, instant).await
}

/// Write MDT timeline fencing markers then a completed deltacommit (Java MOR MDT).
async fn write_metadata_commit(storage: &Storage, instant: &str) -> Result<()> {
    let timeline = format!("{METADATA_BASE}/.hoodie/timeline");
    storage
        .put_file(
            &format!("{timeline}/{instant}.deltacommit.requested"),
            b"{}".as_slice(),
        )
        .await?;
    storage
        .put_file(
            &format!("{timeline}/{instant}.deltacommit.inflight"),
            b"{}".as_slice(),
        )
        .await?;
    // Completion time equals requested for v1; Spark uses a later completion timestamp.
    storage
        .put_file(
            &format!("{timeline}/{instant}_{instant}.deltacommit"),
            b"{}".as_slice(),
        )
        .await?;
    Ok(())
}

/// Parse a Hudi instant timestamp string into epoch millis for RLI storage.
pub fn instant_to_epoch_millis(instant: &str) -> i64 {
    Instant::parse_datetime(instant, "UTC")
        .map(|dt| dt.timestamp_millis())
        .unwrap_or_else(|_| instant.parse::<i64>().unwrap_or(0))
}

/// Format epoch millis as a Hudi timeline instant (`yyyyMMddHHmmssSSS`).
pub fn epoch_millis_to_instant(millis: i64) -> String {
    use chrono::{TimeZone, Utc};
    match Utc.timestamp_millis_opt(millis) {
        chrono::LocalResult::Single(dt) => dt.format("%Y%m%d%H%M%S%3f").to_string(),
        _ => format!("{millis:017}"),
    }
}

fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xffff_ffff_u32;
    for &byte in data {
        crc ^= u32::from(byte);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                (crc >> 1) ^ 0xedb8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}
