/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//! Metadata table bootstrap and files-partition updates.

use std::collections::{BTreeMap, HashMap};

use crate::Result;
use crate::file_group::log_file::writer::LogFileWriter;
use crate::file_group::log_file::{BlockMetadataKey, BlockType};
use crate::hfile::HFileWriter;
use crate::metadata::table::encode::{
    FILES_METADATA_AVRO_SCHEMA, FilesMetadataEntry, encode_all_partitions, encode_files_record,
};
use crate::metadata::table::records::{FilesPartitionRecord, MetadataRecordType};
use crate::storage::Storage;

const METADATA_BASE: &str = ".hoodie/metadata";
const FILES_FILE_ID: &str = "files-0000-0";

/// Create the metadata table properties and its initial files-partition base file.
pub async fn bootstrap_metadata_table(
    data_table_storage: &Storage,
    table_name: &str,
    instant: &str,
) -> Result<()> {
    let properties = format!(
        "# Generated by hudi-rs\n\
         hoodie.table.name={table_name}_metadata\n\
         hoodie.table.type=MERGE_ON_READ\n\
         hoodie.table.base.file.format=HFILE\n\
         hoodie.table.recordkey.fields=key\n\
         hoodie.populate.meta.fields=false\n\
         hoodie.table.version=8\n\
         hoodie.timeline.layout.version=2\n\
         hoodie.table.partition.fields=partition\n"
    );
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/.hoodie/hoodie.properties"),
            properties.into_bytes(),
        )
        .await?;
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/.hoodie/timeline/.keep"),
            b"".as_slice(),
        )
        .await?;

    let empty_files = encode_files_record(
        FilesPartitionRecord::NON_PARTITIONED_NAME,
        MetadataRecordType::Files,
        Vec::<FilesMetadataEntry>::new(),
    )?;
    let all_partitions =
        encode_all_partitions(vec![FilesPartitionRecord::NON_PARTITIONED_NAME.to_string()])?;
    let hfile = HFileWriter::write(
        &[
            (
                FilesPartitionRecord::ALL_PARTITIONS_KEY.to_string(),
                all_partitions,
            ),
            (
                FilesPartitionRecord::NON_PARTITIONED_NAME.to_string(),
                empty_files,
            ),
        ],
        BTreeMap::from([(
            "schema".to_string(),
            FILES_METADATA_AVRO_SCHEMA.as_bytes().to_vec(),
        )]),
    )
    .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
    data_table_storage
        .put_file(
            &format!("{METADATA_BASE}/files/{FILES_FILE_ID}_0-0-0_{instant}.hfile"),
            hfile,
        )
        .await?;
    write_metadata_commit(data_table_storage, instant).await
}

/// Append a files-partition HFile data block to the metadata table log file.
pub async fn update_files_partition(
    data_storage: &Storage,
    instant: &str,
    files: &[(String, String, i64)],
) -> Result<()> {
    let mut by_partition: BTreeMap<String, Vec<FilesMetadataEntry>> = BTreeMap::new();
    for (partition, file_name, size) in files {
        let partition = if partition.is_empty() {
            FilesPartitionRecord::NON_PARTITIONED_NAME.to_string()
        } else {
            partition.clone()
        };
        by_partition
            .entry(partition)
            .or_default()
            .push(FilesMetadataEntry {
                name: file_name.clone(),
                size: *size,
                is_deleted: false,
            });
    }
    let partitions = by_partition.keys().cloned().collect::<Vec<_>>();
    let mut entries = vec![(
        FilesPartitionRecord::ALL_PARTITIONS_KEY.to_string(),
        encode_all_partitions(partitions)?,
    )];
    for (partition, files) in by_partition {
        entries.push((
            partition.clone(),
            encode_files_record(&partition, MetadataRecordType::Files, files)?,
        ));
    }
    let hfile = HFileWriter::write(
        &entries,
        BTreeMap::from([(
            "schema".to_string(),
            FILES_METADATA_AVRO_SCHEMA.as_bytes().to_vec(),
        )]),
    )
    .map_err(|error| crate::error::CoreError::HFile(error.to_string()))?;
    let block = LogFileWriter::write_log_block(
        BlockType::HfileData,
        HashMap::from([(BlockMetadataKey::InstantTime, instant.to_string())]),
        &hfile,
    );
    data_storage
        .put_file(
            &format!("{METADATA_BASE}/files/.{FILES_FILE_ID}_{instant}.log.1_0-0-0"),
            block,
        )
        .await?;
    write_metadata_commit(data_storage, instant).await
}

async fn write_metadata_commit(storage: &Storage, instant: &str) -> Result<()> {
    storage
        .put_file(
            &format!("{METADATA_BASE}/.hoodie/timeline/{instant}_{instant}.commit"),
            b"{}".as_slice(),
        )
        .await?;
    Ok(())
}
