#Updated at 2026-04-09T03:05:26.218823099Z
#Thu Apr 09 03:05:26 UTC 2026
hoodie.table.initial.version=9
hoodie.table.keygenerator.type=NON_PARTITION
hoodie.table.type=MERGE_ON_READ
hoodie.table.metadata.partitions=column_stats,files
hoodie.archivelog.folder=archived
hoodie.table.create.schema={"type"\:"record","name"\:"htestmorfileslicelayouts_2_record","namespace"\:"hoodie.htestmorfileslicelayouts_2","fields"\:[{"name"\:"key","type"\:["null","string"],"default"\:null},{"name"\:"ts","type"\:["null","long"],"default"\:null},{"name"\:"level","type"\:["null","string"],"default"\:null},{"name"\:"severity","type"\:["null","int"],"default"\:null},{"name"\:"partition","type"\:["null","string"],"default"\:null},{"name"\:"round","type"\:["null","int"],"default"\:null}]}
hoodie.timeline.layout.version=2
hoodie.timeline.history.path=history
hoodie.table.checksum=455807046
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.recordkey.fields=key
hoodie.table.name=htestmorfileslicelayouts_2
hoodie.table.format=native
hoodie.timeline.path=timeline
hoodie.datasource.write.hive_style_partitioning=true
hoodie.table.metadata.partitions.inflight=
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
hoodie.database.name=default
hoodie.record.merge.mode=COMMIT_TIME_ORDERING
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.table.version=9
